{
 "title": "Observability Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "instance", "label": "Instance", "query": { "query": "label_values(instance)" } },
   {
    "name": "endpoint",
    "label": "EndPoint",
    "query": {
     "query": "label_values(http_server_requests_seconds_count{uri!=\"/**\", uri!=\"/actuator/prometheus\"},uri)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Process",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "system_cpu_usage{instance=~\"$instance\"}",
       "legendFormat": "system"
      },
      {
       "expr": "process_cpu_usage{instance=~\"$instance\"}",
       "legendFormat": "process-15m"
      }
     ]
    },
    {
     "title": "Thread States",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "jvm_threads_states_threads{instance=~\"$instance\"}",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "Threads",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "jvm_threads_live_threads{instance=~\"$instance\"}",
       "legendFormat": "live"
      },
      {
       "expr": "jvm_threads_daemon_threads{instance=~\"$instance\"}",
       "legendFormat": "daemon"
      },
      {
       "expr": "jvm_threads_peak_threads{instance=~\"$instance\"}",
       "legendFormat": "peak"
      },
      {
       "expr": "process_threads{instance=~\"$instance\"}",
       "legendFormat": "process"
      }
     ]
    },
    {
     "title": "File Descriptors",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "process_files_open_files{instance=~\"$instance\"}",
       "legendFormat": "open"
      },
      {
       "expr": "process_files_max_files{instance=~\"$instance\"}",
       "legendFormat": "max"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Heap  usage",
     "type": "stat",
     "gridPos": { "h": 5, "w": 5, "x": 6, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{instance=~\"$instance\", area=\"heap\"}) / sum(jvm_memory_max_bytes{instance=~\"$instance\", area=\"heap\"}) * 100",
       "legendFormat": "memory"
      }
     ]
    },
    {
     "title": "Non-heap usage",
     "type": "stat",
     "gridPos": { "h": 5, "w": 5, "x": 11, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{instance=~\"$instance\", area=\"nonheap\"}) / sum(jvm_memory_max_bytes{instance=~\"$instance\", area=\"nonheap\"}) * 100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "GC pause duration",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 11, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(jvm_gc_pause_seconds_sum{instance=~\"$instance\"}[1m])/rate(jvm_gc_pause_seconds_count{instance=~\"$instance\"}[1m])",
       "legendFormat": "avg {{action}} ({{cause}})"
      },
      {
       "expr": "jvm_gc_pause_seconds_max{instance=~\"$instance\"}",
       "legendFormat": "max {{action}} ({{cause}})"
      }
     ]
    },
    {
     "title": "GC pressure",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 13, "x": 11, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum(rate(jvm_gc_pause_seconds_sum{instance=~\"$instance\"}[1m])) by (instance) / on(instance) system_cpu_count",
       "legendFormat": "CPU time spent on GC ({{instance}})"
      }
     ]
    }
   ]
  },
  {
   "title": "Inbound Traffic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Status",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 6, "y": 38 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "up{instance=~\"$instance\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total Requests",
     "type": "stat",
     "description": "Last 24h",
     "gridPos": { "h": 4, "w": 4, "x": 10, "y": 38 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(http_server_requests_seconds_count{uri!=\"/actuator/prometheus\"}[24h]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Success Rate",
     "type": "stat",
     "description": "Last 24h",
     "gridPos": { "h": 4, "w": 4, "x": 14, "y": 38 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(http_server_requests_seconds_count{status=~\"2..\", uri!=\"/actuator/prometheus\"}[24h])) / sum(increase(http_server_requests_seconds_count{uri!=\"/actuator/prometheus\"}[24h])) * 100",
       "legendFormat": "2xx"
      }
     ]
    },
    {
     "title": "Latency (2xx, percentile) ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 42 },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{uri=~\"$endpoint\", instance=~\"$instance\", status=~\"2..\"} [5m])) by(le))",
       "legendFormat": "99th"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket{uri=~\"$endpoint\", instance=~\"$instance\", status=~\"2..\"} [5m])) by(le))",
       "legendFormat": "95th"
      },
      {
       "expr": "histogram_quantile(0.50, sum(rate(http_server_requests_seconds_bucket{uri=~\"$endpoint\", instance=~\"$instance\", status=~\"2..\"} [5m])) by(le))",
       "legendFormat": "50th"
      }
     ]
    },
    {
     "title": "Request Status Code",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 13, "x": 11, "y": 42 },
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{uri=~\"$endpoint\", instance=~\"$instance\", status=~\"2..\"}[5m]))",
       "legendFormat": "2xx"
      },
      {
       "expr": "sum(rate(http_server_requests_seconds_count{uri=~\"$endpoint\", instance=~\"$instance\", status=~\"3..\"}[5m]))",
       "legendFormat": "3xx"
      },
      {
       "expr": "sum(rate(http_server_requests_seconds_count{uri=~\"$endpoint\", instance=~\"$instance\", status=~\"4..\"}[5m]))",
       "legendFormat": "4xx"
      },
      {
       "expr": "sum(rate(http_server_requests_seconds_count{uri=~\"$endpoint\", instance=~\"$instance\", status=~\"5..\"}[5m]))",
       "legendFormat": "5xx"
      }
     ]
    }
   ]
  },
  {
   "title": "Outbound Traffic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Avg. response time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 4 },
     "targets": [
      {
       "expr": "sum(rate(http_client_requests_seconds_sum{}[5m])/rate(http_client_requests_seconds_count{}[5m])) by (uri)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Request Status Code",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 13, "x": 11, "y": 4 },
     "targets": [
      {
       "expr": "sum(rate(http_client_requests_seconds_count{status=~\"2..\"}[5m]))",
       "legendFormat": "2xx"
      },
      {
       "expr": "sum(rate(http_client_requests_seconds_count{status=~\"3..\"}[5m]))",
       "legendFormat": "3xx"
      },
      {
       "expr": "sum(rate(http_client_requests_seconds_count{status=~\"4..\"}[5m]))",
       "legendFormat": "4xx"
      },
      {
       "expr": "sum(rate(http_client_requests_seconds_count{status=~\"5..\"}[5m]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Error volume per minute",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum(rate({level=\"ERROR\"}[5m])) by(app) * 60"
    }
   ]
  },
  {
   "title": "New Panel",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "{app=\"name_IS_UNDEFINED\"}"
    }
   ]
  }
 ]
}